name: Publish docker image
on: 
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the rep
        uses: actions/checkout@v2
      - name: Log into github Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: take out docker tags
        uses: 
      - name: Build container images
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/urlshortner:latest
